SET CPU_TYPE=IOTKit_CM33_FP_VHT
SET CPU_VENDOR=ARM
SET UV2_TARGET=Cortex-M33_MPS2
SET CPU_CLOCK=0x00B71B00
"C:\Program Files (x86)\Arm GNU Toolchain arm-none-eabi\13.2 Rel1\bin\arm-none-eabi-gcc" @".\objects\platform.__i"
"C:\Program Files (x86)\Arm GNU Toolchain arm-none-eabi\13.2 Rel1\bin\arm-none-eabi-gcc" @".\objects\serial.__i"
"C:\Program Files (x86)\Arm GNU Toolchain arm-none-eabi\13.2 Rel1\bin\arm-none-eabi-gcc" @".\objects\main.__i"
"C:\Program Files (x86)\Arm GNU Toolchain arm-none-eabi\13.2 Rel1\bin\arm-none-eabi-gcc" @".\objects\eventrecorder.__i"
"C:\Program Files (x86)\Arm GNU Toolchain arm-none-eabi\13.2 Rel1\bin\arm-none-eabi-gcc" @".\objects\startup_iotkit_cm33.__i"
"C:\Program Files (x86)\Arm GNU Toolchain arm-none-eabi\13.2 Rel1\bin\arm-none-eabi-gcc" @".\objects\system_iotkit_cm33.__i"
"C:\Program Files (x86)\Arm GNU Toolchain arm-none-eabi\13.2 Rel1\bin\arm-none-eabi-gcc" @".\objects\core_list_join.__i"
"C:\Program Files (x86)\Arm GNU Toolchain arm-none-eabi\13.2 Rel1\bin\arm-none-eabi-gcc" @".\objects\core_matrix.__i"
"C:\Program Files (x86)\Arm GNU Toolchain arm-none-eabi\13.2 Rel1\bin\arm-none-eabi-gcc" @".\objects\core_state.__i"
"C:\Program Files (x86)\Arm GNU Toolchain arm-none-eabi\13.2 Rel1\bin\arm-none-eabi-gcc" @".\objects\core_util.__i"
"C:\Program Files (x86)\Arm GNU Toolchain arm-none-eabi\13.2 Rel1\bin\arm-none-eabi-gcc" @".\objects\core_main.__i"
"C:\Program Files (x86)\Arm GNU Toolchain arm-none-eabi\13.2 Rel1\bin\arm-none-eabi-gcc" @".\objects\perf_counter.__i"
"C:\Program Files (x86)\Arm GNU Toolchain arm-none-eabi\13.2 Rel1\bin\arm-none-eabi-gcc" @".\objects\systick_wrapper_gcc.__i"
"C:\Program Files (x86)\Arm GNU Toolchain arm-none-eabi\13.2 Rel1\bin\arm-none-eabi-gcc" @".\objects\core_portme.__i"
"C:\Program Files (x86)\Arm GNU Toolchain arm-none-eabi\13.2 Rel1\bin\arm-none-eabi-gcc" @".\Objects\GCC_TE~1.LNP"
